services:
  - type: web
    name: seminar-suite
    runtime: docker
    plan: free
    healthCheckPath: /login
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: cloud
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
